cd env && touch .env .env.test
echo
APP_ENVIRONMENT="staging"
PORT="8080"

# Database Config
DB_HOST=$STAGING_DB_HOST
DB_USERNAME=$STAGING_DB_USERNAME
DB_PASSWORD=$STAGING_DB_PASSWORD
DB_NAME=$STAGING_DB_NAME
DB_PROTOCOL = $STAGING_DB_PROTOCOL
ADDITIONAL_DATA = $STAGING_ADDITIONAL_DATA | tee .env

cat .env

echo
APP_ENVIRONMENT="test"
PORT="6060"

# Database Config
DB_HOST=$STAGING_DB_HOST
DB_USERNAME=$STAGING_DB_USERNAME
DB_PASSWORD=$STAGING_DB_PASSWORD
DB_NAME=$STAGING_DB_NAME_TEST
DB_PROTOCOL = $STAGING_DB_PROTOCOL
ADDITIONAL_DATA = $STAGING_ADDITIONAL_DATA | tee .env.test
cd ../
